apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vtlqiojiy-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:f66e82c567cc50a278e9a35affcbff43e76ed496@sha256:7fa5d5ccb9a4f4b0159524321183143a6dd87b13ef9fe542fd1605f0cb23699d
          name: container-image
